### PR TITLE
Metric module

### PR DESCRIPTION
**Pull request by klemen1999**
`MetricModule` class that can be attached to any module in order to handle its metrics. Built based on config, has separate collections for train, val and test metrics and abstract the update/compute/reset functions.
Also added `METRICS` registry to allow for custom metrics.

### CODE REVIEW

**Comment by klemen1999** [comment]
> Will the head define a default metrics module in that case?

Yeah I think defining default metric modules at the start of the head that uses it is the right place since we can check if these are already specified in the config or not and we also have access to all head attributes that we can then plug into metric module params (e.g. n_classes is a common attribute that is needed for metric module init)

**Comment by tersekmatija** [comment]
> Yeah I think defining default metric modules at the start of the head that uses it is the right place since we can check if these are already specified in the config or not and we also have access to all head attributes that we can then plug into metric module params (e.g. n_classes is a common attribute that is needed for metric module init)

Ok that makes sense. Would we want to check also if the parameters defined in the config deviate from the default ones defined in the head and replace it in that case?
How would we handle newly requested vs existing metric?

**Comment by tersekmatija** [comment]
Ok great, this sounds good.

**Comment by klemen1999** [comment]
Going to close this PR as this will be part of the topology refactor

**Pull request closed without merging**
