### PR TITLE
Heads refactor

### PR DESCRIPTION
**Pull request by klemen1999**
Notable changes:
- Updated `YoloV6Head`, `IKeypointHead` and `RepVGGNeck` to work with `num_heads` and `attach_index` . Now 2,3 or 4 heads are supported and can be attached to different layers.
- Updated `BaseHead` to be an abstract class, now we validate `attach_index` and raise a warning for unused parameters (same also for `BaseBackbone` and `BaseNeck`).
- Added `anchors_from_dataset` function to generate anchors at runtime if `IKeypointHead` `anchors` parameter is set to None. This is checked when we build/validate Config.
- Added head tests.
- Removed `IKeypointMultiHead` since this is now supported by `IKeypointHead` with `num_heads` parameter.
- Removed `EffiDeHead` as a standalone head and is now one of `YoloV6Head` blocks.

### CODE REVIEW

**Comment by kozlov721** [comment]
For the anchors computing, it would make sense to me to add an option to compute such dataset statistics during the LDF creation. So it would be stored together with the dataset as a metadata or something like that. We could also compute other things as well, like the mean/std of the dataset and possibly some more stuff in the future. 

In the `models`, we would first look if it's not already in the dataset and only then we would compute it. Otherwise, we would have to either manually rewrite the computed anchors to the config or compute it again every time.

**Review by kozlov721 — COMMENTED** [review]
LGTM

**Comment by tersekmatija** [comment]
> In the models, we would first look if it's not already in the dataset and only then we would compute it. Otherwise, we would have to either manually rewrite the computed anchors to the config or compute it again every time.

Yes, I quite like this approach of it being linked to the dataset. As well as having some other features computed for it. We'll have to think through though when to create them -- perhaps on versioning or through a manual request. Automatically though might not be always required since we need them for V5/V7 yolos and not for V6.

**Review by tersekmatija — APPROVED** [review]

**Comment by klemen1999** [comment]
I agree, in the future functions like anchor generation or computing mean/std of the dataset should be part of the luxonis-ml. But if possible, I would make it part of some sort of LDF metadata which is computed on creation of new version (e.g. compute anchors everytime bounding box annotations are present). It could be also implemented as a function which is called at runtime but then for example each time we start keypoint training we have to recompute anchors (if they were not saved from last time). I guess it depends on how time consuming this functions are/will be.

**Comment by tersekmatija** [comment]
Yeah I'd store as metadata of either the versions or the dataset in general. Though seems to be more useful if on version directly. I think we can add this to backlog. I'd still make this triggerable somehow in the future as perhaps it might not make sense computing all of that for each version.

**Review by kozlov721 — APPROVED** [review]

**Pull request merged**
